// Initial game list with Player and Admin links. When using Google Sheets, this is fallback/static data.
const GAMES_DATA = [
  { name: "Blue Dragon", playerUrl: "http://app.bluedragon777.com/", adminUrl: "https://agent.bluedragon777.com/Login.aspx" },
  { name: "Cash Frenzy", playerUrl: "https://www.cashfrenzy777.com/", adminUrl: "https://agentserver.cashfrenzy777.com/admin/login" },
  { name: "Cash Machine", playerUrl: "https://www.cashmachine777.com/", adminUrl: "http://agentserver.cashmachine777.com/admin/login" },
  { name: "Casino Ignite", playerUrl: "https://download.casinoignitee.vip/", adminUrl: "https://agent.casinoignitee.vip/" },
  { name: "Egame", playerUrl: "https://www.egame99.club/", adminUrl: "https://pko.egame99.club/#/index" },
  { name: "Firekirin", playerUrl: "https://firekirin.com/", adminUrl: "https://firekirin.xyz:8888/" },
  { name: "Game Room", playerUrl: "https://www.gameroom777.com/", adminUrl: "https://agentserver1.gameroom777.com/admin/login" },
  { name: "Game Vault", playerUrl: "https://download.gamevault999.com/", adminUrl: "https://agent.gamevault999.com/login" },
  { name: "Golden Dragon", playerUrl: "https://playgd.mobi/SSLobby/3865.0/web-mobile/index.html", adminUrl: "https://pos.goldendragoncity.com/pos/5016483" },
  { name: "Joker", playerUrl: "https://www.joker777.win/", adminUrl: "http://agent.joker777.win/" },
  { name: "Juwa", playerUrl: "https://dl.juwa777.com/", adminUrl: "https://ht.juwa777.com/login" },
  { name: "Juwa 2.0", playerUrl: "https://m.juwa2.com/", adminUrl: "https://agent.juwa2.com/" },
  { name: "King of Pop", playerUrl: "https://www.slots88888.com/m", adminUrl: "http://agentserver.slots88888.com/" },
  { name: "Mafia", playerUrl: "https://www.mafia77777.com/", adminUrl: "http://agentserver.mafia77777.com/" },
  { name: "Mega Spin", playerUrl: "https://www.megaspinsweeps.com/", adminUrl: "https://megaspinpay.com/default.aspx" },
  { name: "Milkyway", playerUrl: "https://milkywayapp.xyz/", adminUrl: "https://milkywayapp.xyz" },
  { name: "Mr All in One", playerUrl: "http://www.mrallinone777.com/", adminUrl: "http://agentserver.mrallinone777.com/admin" },
  { name: "Orion Star", playerUrl: "http://start.orionstars.vip:8580/index.html", adminUrl: "https://orionstars.vip:8781" },
  { name: "Panda Master", playerUrl: "https://pandamaster.vip:8888/index.html", adminUrl: "https://pandamaster.vip/default.aspx" },
  { name: "RiverSweep", playerUrl: "https://bet777.eu/", adminUrl: "https://river-pay.com/office/login" },
  { name: "Sirus", playerUrl: "https://m.gamesirius999.com/", adminUrl: "http://h5.gamesirius999.com/" },
  { name: "UltraPanda", playerUrl: "https://www.ultrapanda.club/", adminUrl: "https://ht.ultrapanda.mobi/" },
  { name: "VBlink", playerUrl: "https://www.vblink777.club/", adminUrl: "https://gm.vblink777.club/" },
  { name: "Vegas Roll", playerUrl: "https://www.vegas-roll.com/", adminUrl: "http://backend.vegas-roll.com/" },
  { name: "Vegas Sweeps", playerUrl: "https://m.lasvegassweeps.com/", adminUrl: "https://agent.lasvegassweeps.com/adminList" },
  { name: "VegasX", playerUrl: "https://www.vegas-x.org/", adminUrl: "https://admin.vegas-x.org/login" },
  { name: "Win Star", playerUrl: "http://www.winstar99999.com/", adminUrl: "http://agent.winstar99999.com/" },
  { name: "Yolo", playerUrl: "https://yolo777.game/", adminUrl: "https://agent.yolo777.game/" }
];
